name: macOS

on:
  push:
    branches: ["**"]

jobs:
  macOS:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build SwiftGodotKit
      run: swift build --target SwiftGodotKit -v
    - name: Run tests
      run: swift test -v
